### PR TITLE
Locate V2 API

### PR DESCRIPTION
**Pull request by olgagalchenko**
# Changes
Given the lack of activity on https://github.com/m-lab/ndt7-client-ios/pull/77, I decided to open another PR addressing the feedback from @miguelangelnet.

- Updated this client to use Locate V2 API
- Updated tests

# Further resources:
[Location V2 API](https://pkg.go.dev/github.com/m-lab/locate/api/v2)
[Requiring access tokens blog post](https://www.measurementlab.net/blog/why-access-tokens/#requiring-access-tokens-for-ndt7)

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/ndt7-client-ios/80)

### CODE REVIEW

**Comment by stephen-soltesz** [comment]
Thank you for this! While I don't speak swift, I'll still take a look today.

**Review by stephen-soltesz — CHANGES_REQUESTED** [review]
Added a few comments and clarifying questions. This looks great.

> *[Reviewable](https://reviewable.io/reviews/m-lab/ndt7-client-ios/80#-:-MUnmR8KAradXFB3cHNR:b-x02455)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @olgagalchenko)

___
*[NDT7.xcodeproj/project.pbxproj, line 1184 at r1](https://reviewable.io/reviews/m-lab/ndt7-client-ios/80#-MUnlVBkAC2JguKURcUm:-MUnlVBkAC2JguKURcUn:bnuguf6) ([raw file](https://github.com/m-lab/ndt7-client-ios/blob/774ab254441e44a1d1a48c7e5abd7476e72cfa11/NDT7.xcodeproj/project.pbxproj#L1184)):*
> ```
> 				CODE_SIGN_STYLE = Manual;
> 				DEFINES_MODULE = YES;
> 				DEVELOPMENT_TEAM = 44JL34SSKJ;
> ```

Is this particular to a private set of signing keys?

Is there a standard way of managing differences like these for a package that's meant to be used by more than one group?
___
*[Sources/Constants.swift, line 59 at r1](https://reviewable.io/reviews/m-lab/ndt7-client-ios/80#-MUngUY41W-DGAgs1ZKK:-MUngUY5BdSXG27OAELw:b-9nim67) ([raw file](https://github.com/m-lab/ndt7-client-ios/blob/774ab254441e44a1d1a48c7e5abd7476e72cfa11/Sources/Constants.swift#L59)):*
> ```Swift
> 
>         /// Discover closer MLab Server
>         public static let url = "https://\(hostname)/\(path)"
> ```

I recommend including a parameter providing a client name , e.g. `?client_name=ndt7-client-ios`

If possible, I recommend also including the client version, e.g. `&client_version=<version>`.

Please include at least the client name.
___
*[Sources/NDT7Settings.swift, line 51 at r1](https://reviewable.io/reviews/m-lab/ndt7-client-ios/80#-MUnhnINAbRt8inp6oCR:-MUnhnINAbRt8inp6oCS:bl8d070) ([raw file](https://github.com/m-lab/ndt7-client-ios/blob/774ab254441e44a1d1a48c7e5abd7476e72cfa11/Sources/NDT7Settings.swift#L51)):*
> ```Swift
>     /// Initialization.
>     public init(timeout: NDT7Timeouts = NDT7Timeouts(),
>                 skipTLSCertificateVerification: Bool = true,
> ```

I suggest setting this to be false by default. Are there any certs that are not verifying currently?
___
*[Tests/NDT7TestTests.swift, line 34 at r1](https://reviewable.io/reviews/m-lab/ndt7-client-ios/80#-MUnjy2u011agnE9NQhJ:-MUnjy2u011agnE9NQhK:bmpivwz) ([raw file](https://github.com/m-lab/ndt7-client-ios/blob/774ab254441e44a1d1a48c7e5abd7476e72cfa11/Tests/NDT7TestTests.swift#L34)):*
> ```Swift
>     """.data(using: .utf8)
> 
>     let jsonServerDataNoURLs = """
> ```

Regarding test cases for the future. It's also possible for the locate API to return an error without any results. e.g. http://locate.measurementlab.net/v2/nearest/ndt/foo 

```
{
  "error": {
    "type": "config",
    "title": "Unknown service: ndt/foo",
    "status": 400
  }
}
```

And, though this is not implemented, the Locate v2 API may return a "next_request" without results, to defer a client. https://github.com/m-lab/locate/blob/master/api/v2/api.go#L27 

Neither of these need block this PR.

**Review by stephen-soltesz — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/ndt7-client-ios/80)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @olgagalchenko)

___
*[NDT7.xcodeproj/project.pbxproj, line 1184 at r1](https://reviewable.io/reviews/m-lab/ndt7-client-ios/80#-MUnlVBkAC2JguKURcUm:-MUnmfz29VXE8zLi8IC5:b-319ahi) ([raw file](https://github.com/m-lab/ndt7-client-ios/blob/774ab254441e44a1d1a48c7e5abd7476e72cfa11/NDT7.xcodeproj/project.pbxproj#L1184)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Is this particular to a private set of signing keys?

Is there a standard way of managing differences like these for a package that's meant to be used by more than one group?
</blockquote></details>

A related question -- will we be able to update the https://cocoapods.org/pods/NDT7 with this value? Or, is this unrelated to that?

**Comment by olgagalchenko** [comment]
Thanks for the review, @stephen-soltesz! 

I woke up this morning thinking, did I forget to revert that code signing change? I had changed it so I could build the sample app on my phone. Will revert now. Good catch!

**Review by stephen-soltesz — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/ndt7-client-ios/80)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @olgagalchenko)

**Review by stephen-soltesz — COMMENTED** [review]
:lgtm: -- @olgagalchenko I also added you as a collaborator for this repo. I believe that should allow you to merge the change or review any future changes submitted by others.

> *[Reviewable](https://reviewable.io/reviews/m-lab/ndt7-client-ios/80#-:-MUo87XY2YpiCqXczU2n:b97mvha)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @olgagalchenko)

**Pull request merged**
